### ISSUE TITLE
NISの稼働時間の表示

### ISSUE THREAD

**Issue by mizunashi** [44uk/nem-harvesting-slot-viewer#1]
やたら空きスロットが余っている場合、逆に安定していないのかな？と不安になります。
できればNISのアップタイムが分かると嬉しいです。

**Comment by 44uk** [comment]
確かに、選ぶには大事な基準ですね。検討してみます。

**Comment by 44uk** [comment]
https://github.com/44uk/nem-harvesting-slot-viewer/commit/dd01bf19a908fe902d729a98a7bd3051b1b58cce
こちらのコミットにて対応しました。
http://hydrographer-ape-87625.bitballoon.com/
公開済みです。

**Comment by mizunashi** [comment]
Great!
